### ISSUE TITLE
Use Nodemailer to Implement contact page

### ISSUE THREAD

**Issue by cwolberg** [luiangvia/Project_2#72]
Elena has been working on this, but may need help troubleshooting.

Elena's code (below link)

https://github.com/meishal7/contactform

**Comment by cwolberg** [comment]
Going to drop this unless it can be done sometime tonight. Lemme know. :)

**Comment by cwolberg** [comment]
Out of time, closing

**Comment by cwolberg** [comment]
Re-opening this. 

Elena, what was the last error you were getting while testing this? 

Can you create a new branch of what you have?

Anyone else have time to help with this one?

**Comment by cwolberg** [comment]
Elena and I's last conversation on the issue, below

Elena Mudrakova [4:37 PM]
tagun@DESKTOP-IEQINIB MINGW64 ~/Desktop/Projects/Project_2/test/Node-Mailer-master/Node-Mailer-master (Elena)
$ node server.js
Express Started on Port 3000
express deprecated res.sendfile: Use res.sendFile instead server.js:28:6
{ to: 'meishal7@gmail.com', subject: 'gg', text: 'vff' }
{ Error: Missing credentials for "PLAIN"
   at SMTPConnection._formatError (C:\Users\tagun\Desktop\Projects\Project_2\te
st\Node-Mailer-master\Node-Mailer-master\node_modules\nodemailer\lib\smtp-connec
tion\index.js:781:19)
   at SMTPConnection.login (C:\Users\tagun\Desktop\Projects\Project_2\test\Node-Mailer-master\Node-Mailer-master\node_modules\nodemailer\lib\smtp-connection\index.js:452:38)
   at connection.connect (C:\Users\tagun\Desktop\Projects\Project_2\test\Node-Mailer-master\Node-Mailer-master\node_modules\nodemailer\lib\smtp-transport\index.js:271:32)
   at SMTPConnection.once (C:\Users\tagun\Desktop\Projects\Project_2\test\Node-Mailer-master\Node-Mailer-master\node_modules\nodemailer\lib\smtp-connection\index.js:209:17)
   at Object.onceWrapper (events.js:273:13)
   at SMTPConnection.emit (events.js:182:13)
   at SMTPConnection._actionEHLO (C:\Users\tagun\Desktop\Projects\Project_2\test\Node-Mailer-master\Node-Mailer-master\node_modules\nodemailer\lib\smtp-connection\index.js:1309:14)
   at SMTPConnection._processResponse (C:\Users\tagun\Desktop\Projects\Project_2\test\Node-Mailer-master\Node-Mailer-master\node_modules\nodemailer\lib\smtp-connection\index.js:940:20)
   at SMTPConnection._onData (C:\Users\tagun\Desktop\Projects\Project_2\test\Node-Mailer-master\Node-Mailer-master\node_modules\nodemailer\lib\smtp-connection\index.js:746:14)
   at TLSSocket.SMTPConnection._onSocketData (C:\Users\tagun\Desktop\Projects\Project_2\test\Node-Mailer-master\Node-Mailer-master\node_modules\nodemailer\lib\smtp-connection\index.js:189:46)
code: 'EAUTH', command: 'API' }

tagun@DESKTOP-IEQINIB MINGW64 ~/Desktop/Projects/Project_2/test/Node-Mailer-master/Node-Mailer-master (Elena)

Chris, if I see this line { to: 'meishal7@gmail.com', subject: 'gg', text: 'vff' } in node despite of err after that it means that its working? bec I see the massage

Elena Mudrakova [4:48 PM]
no, it's not
